"""add strong_areas and missing_skills to matches

Revision ID: 78293f954a8e
Revises: f6658728ec45
Create Date: 2026-08-15 22:30:36.852031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78293f954a8e'
down_revision: Union[str, None] = 'f6658728ec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('strong_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'missing_skills')
    op.drop_column('matches', 'strong_areas')
    # ### end Alembic commands ###